[project]
authors = ["Staszek Pasko <staszek@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Advent of Code 2023 (in Mojo)"
name = "aoc2023"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.5.0,<25"
